### ISSUE TITLE
Master Issue with 4 main topics: Equivalence, Gate Report, TechOps, EdgeVideo

### ISSUE THREAD

**Issue by marcoherbst** [evercam/ex_nvr#252]
The purpose of this issue is to group upcoming tasks into the 4 themes above. This is relevant to ExNVR <> Evercam integration and will also link to other non-public repositories. 

**Equivalence:** Features currently supported by Evercam for other NVRs
- [ ] Ability to access WebUI of Camera via ExNVR ( This is solved with the NetbirdVPN )
- [ ] Ability to access snapshot URL (and maybe others) on camera via ExNVR (as above)
- [ ] Ability to access Camera RTSP feed (or equivalent) via ExNVR ( Solved with RTSP restreamer in v0.10 )

NB. All 3 of these issues could be solved, in a rather simple manner, with port forwarding on the NVR.

**TechOps** Deployment, Monitoring, Storage Management
- [ ] HDD Monitoring https://github.com/evercam/ex_nvr/issues/19 
- [ ] Deployment (Nerves) https://github.com/evercam/ex_nvr/issues/246
- [ ] Deployment https://github.com/evercam/ex_nvr/issues/155

**EdgeVideo** Improvements to Evercam experience beyond current functionality.
- [x] https://github.com/evercam/evercam-backend/issues/3232 
- [x] https://github.com/evercam/ex_nvr/issues/157
- [x] https://github.com/evercam/ex_nvr/issues/283

**Gate Report:**
- [ ] ANPR https://github.com/evercam/ex_nvr/issues/179

**Comment by marcoherbst** [comment]
Things have moved on a bit since writing this issue. I think that better managed project roadmap allows it to be closed https://github.com/orgs/evercam/projects/21
